Social-Network/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|


//Route::get('/', 'WelcomeController@index');

// Home Page
Route::get('/', function () {
    //return view('posts.index');
 
    $img = Image::make('foo.jpg')->resize(300, 200);

    return $img->response('jpg');

});

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
*/




// Home Page
Route::get('/', function () {
    return view('posts.index');
});

// Submit the Registration Form
Route::post('register', 'Reg\RegistrationController@postRegister');

// Get the Registration Page
Route::get('register', 'Reg\RegistrationController@register');

// Get the Login Page
Route::get('login', 'Login\LoginController@login');

// Submit the Login Page
Route::post('login', 'Login\LoginController@postLogin');

// Log the User out
Route::get('logout', 'Login\LoginController@logout');

Route::post('user/search', array('as' => 'user.search', 'uses' => 'User\UserController@search'));

// Controllers
Route::controllers([
   'password' => 'Auth\PasswordController',
   'login' => 'Login\LoginController',
   'reg' => 'Reg\RegistrationController'
]);

// Post controller routes
Route::resource('post', 'Post\PostController');

// User controller routes
Route::resource('user', 'User\UserController');

Social-Network/app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'dayOfBirth', 'monthOfBirth', 'yearOfBirth', 'email', 'password', 'image'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
}

Social-Network/app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\User;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Validator;
use Input;
use DB;
use Image;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        // get all the users
        $user = User::all();

        return view('users.view')->with(compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        // get the users id
        $user = User::find($id);

        // calculate the users age
        $dob = $user->yearOfBirth;
        $currentYear = date('Y');
        $dob = $currentYear - $dob;

        $image = $user->image;
        //$image = Input::file($userImage);
        //$image = $_FILES[$user->image];
       // $image = Input::file($user->image)->getRealPath();

        return view('users.show')->with(compact('user', 'dob', 'image'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        // get the user's id
        $user = User::find($id);
        $year = $user->yearOfBirth;
        $currentYear = date('Y');
        // return the view with the $id
        return view('users.edit')->with(compact('user', 'currentYear', 'year'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        // get the user's id
        $user = User::find($id);

        $validator = $this->validator($request->all());

         if($validator->passes()){

           // Get all the inputs
                $input = $request->all();
                // assign values
                $user->name = $input['name'];
                $user->dayOfBirth = $input['dayOfBirth'];
        		$user->monthOfBirth = $input['monthOfBirth'];
        		$user->yearOfBirth = $input['yearOfBirth'];
        		$user->email = $input['email'];
        		$user->password = bcrypt($request['password']);
        		
        		if ($request->hasFile('image')) {
                 
                    // get the file
                    $image = $request->file('image');
                    // change the name of the file
                    $filename  = $user->email . '.' .'png';
                    // save the new image to public/images
                    $path = public_path('images/users/' . $filename);
                    // create a new Image data
                    $path = Image::make($image->getRealPath())->resize(300, 300)->save($path)->encode('data-url');
                    // save the image data to its user
                    $user->image = $path;
                   
                }	
		
		 
    		// save the user Object
    	    $user->save();	
		
          
           return redirect()->route('user.show', [$user->id]);
        

        } else{

            return redirect()->back()->withErrors($validator);
        }
        
    }

     /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255',
          //  'password' => 'required|confirmed|min:6',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        // get the user's id
        $user = User::find($id);

        $user->delete();

        return redirect()->route('post.index');
    }

    public function search(){
    
        $input = Input::all();
        
        $i = $input['query'];
        $mySearch = $i;
        
    //  $userImage = User::all();
    
        //$searchuser = User::where('email','like',$i)->get();
        
         $sql =  "SELECT * FROM users WHERE name like ?";
        $user = DB::select($sql, array("%$i%"));
     
        return view('users.view')->with(compact('user', 'mySearch'));;
        // return View::make('users.view')->with(compact('mySearch', 'searchuser'));
    //  return View::make('users.search')->with('mySearch',$mySearch)->with('searchuser', $searchuser);
    }
}

Social-Network/resources/views/users/edit.blade.php
@extends('reg.layout')

@section('title')
Update User
@stop

 @section('content')
    
    <div class="col-sm-1">
           
    </div>


        <div class="col-sm-9">
                
          <h3>Edit Details</h3>
                <br>
                <br>
                {!! Form::model($user, array('method' => 'PUT', 'files' => true, 
                    'route' => array('user.update', $user->id))) !!}
              
              <div class="form-group">
                 {!! Form::label('name', 'Name: ') !!}
                 {!! Form::text('name', $user->name, array('class' => 'form-control')) !!}
                 {!! $errors->first('name') !!}
              </div>

              <div class="form-group">
                {!! Form::label('date_of_birth', 'Date Of Birth: ') !!} <br>
                {!! Form::selectRange('dayOfBirth', $user->dayOfBirth, 01, 31) !!}
                {!! Form::selectMonth('monthOfBirth', $user->monthOfBirth) !!}

                {!! Form::selectYear('yearOfBirth', $year, $currentYear, $currentYear) !!}       
              </div>

              <div class="form-group">
                 {!! Form::label('email', 'Email: ') !!}
                 {!! Form::email('email', $user->email, array('class' => 'form-control')) !!}
                 {!! $errors->first('email') !!}
              </div>
              
              <div class="form-group">
                {!! Form::label('image', 'Profile Image: ') !!}
                {!! Form::file('image') !!}
              </div>
              
              
              {!! Form::submit('Save', array('class' => 'btn btn-success')) !!}
              {!! Form::close() !!}
             
         
        </div>
        
    <div class="col-sm-1">
           
    </div>

 @stop

Social-Network/resources/views/users/layout.blade.php
<!DOCTYPE html>
<!-- List item. -->
<html>

 <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>@yield('title')</title>
    
    <!-- Icon -->
    <link rel="icon" href="{{{ asset('favicon.ico') }}}">
    
    <!-- Custom styles for this template -->
    
    <link rel="stylesheet" href="{{{ asset('css/styles.css') }}}">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Bootstrap core JavaScript
    ================================================== -->
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  </head>

<body>
  
  <div class="container">  
     
          <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Social Network</a></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              
               <li><a href="{{ URL::to('./') }}">Home</a></li>
                
              @if (Auth::check())
                <li>
                  <a href="{{{ url("logout") }}}" role="button">Logout</a>
                </li>
              @else
                <li>
                  <a href="{{{ url("login") }}}">Login</a>
                  <li><a href="{{ URL::to('register') }}">Sign Up</a></li>
                </li>
              @endif
               
                <li>
                    
                </li>
               
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

       <div class="col-lg-4">
              
              </div>
              
           <div class="col-lg-8">
               {!! Form::open(array('route' => array('user.search'))) !!}
              <div class="input-group">
                 {!! Form::text('query', $mySearch, array('placeholder' => 'Search user by name', 'class' => 'form-control')) !!}
                  <span class="input-group-btn">
                    {!! Form::submit('Search', array('class' => 'btn btn-default')) !!}
                    {!! Form::close() !!}
                  </span>
              </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->

      
      @section('content')
      @show
      
  </div> <!-- /container -->
  
</body>
</html>

Social-Network/resources/views/users/show.blade.php
@extends('reg.layout')

@section('title')
Database Search Results
@stop

@section('content')
  <div class="row">
    <div class="col-sm-2">
         
      
            
          
    </div>
    <div class="col-sm-10">
           <h4>Profile Info</h4>
            <ul class="list-group">
                
                <li class="list-group-item">
                     
                        <div class='post'>
                         <img class='post-image' src="{{{ $user->image }}}" alt='photo' />
                        
                       
                          <br>
                     
                            <strong style="text-align:right; margin-left:20px;">Name:</strong> {{{ $user->name }}}
                            <br>
                            <strong style="text-align:right; margin-left:20px;">Age:</strong> {{{ $dob }}}
                          <br>
                              <strong style="text-align:right; margin-left:20px;">Email:</strong> {{{ $user->email }}}
                          <br>
                        </div>
                        <p>
                            {!! Form::open(array('method' => 'DELETE', 'route' => 
                                 array('user.destroy', $user->id))) !!}
                            {!! Form::submit('Delete', array('class' => 'btn btn-danger')) !!}
                            <a class="btn btn-primary" href="{{ route('user.edit', [$user->id]) }}" role="button">Edit</a>
                                 
                           
                                 @if(Auth::id() == $user->id)
                                
                                @else
                                 <a class="btn btn-success" href="#" role="button">Add Friend</a>
                                @endif
                            
                            {!! Form::close() !!}
                        </p>
                       
                 </li>
                
                 
                
            </ul>
          
    </div>
  </div>
 @stop

Social-Network/resources/views/users/view.blade.php
@extends('users.layout')

@section('title')
Database Search Results
@stop

@section('content')


      <div class="row">
        

        <div class="col-sm-2">
            @if (Auth::check())
                              
                <p>
                  <strong>Welcome:</strong> {!! Auth::user()->name !!} 
                </p> 
               
            @endif
        </div>


       
        <div class="col-sm-10">
           
            <br>
            <br>
             
            @if (count($user) == 0)
             
              <p>No USER found.</p>
            
            @else 
              
            <h5> {{ Count($user) }} users found</h5>
               
              <ul class="list-group">
                  
                  <li class="list-group-item">
                  
                    @foreach($user as $users)
                      
                      <div class='post'>
                          
                           <img class='post-image' src="{{{ $users->image }}}" alt='photo' />
                          <br>
                          <strong style="text-align:right; margin-left:20px;">Name:</strong> {{{ $users->name }}}
                          <br>
                           
                          <br>
                          
                          <br>
                             
                      </div>
                        
                      <p>
                        <a class="btn btn-info" href="{{ route('user.show', [$users->id]) }}" role="button">Profile</a>
                      <p>
                    
                    @endforeach
                  
                  </li>
    
              </ul>
      
                    
            @endif
          
        </div>


        
      </div>
      
@stop